### ISSUE TITLE
Too Many Requests for url

### ISSUE THREAD

**Issue by jexp** [TheR1D/shell_gpt#17]
For my very first request with a newly generated API Key, I got this:

```
HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/completions
```

Any idea what could be the cause?

I only found this page, which was not helpful.

**Comment by TheR1D** [comment]
It happens because of OpenAI API limitations. You can read more about request limits [here](https://platform.openai.com/docs/guides/rate-limits/overview)
You can track your usage in the [dashboard](https://platform.openai.com/account/usage)
Note that limitation applies on both [OpenAI's playground](https://platform.openai.com/playground) and this tools which is  using their API.
You can still use `sgpt` after a while, when daily limits will be refreshed.

**Comment by brona90** [comment]
I encountered this problem with a brand-new account on the first call, so this answer isn't entirely accurate.

**Comment by effective-ai** [comment]
just install hell-gpt and make first question - after that I received 'HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions'
![image](https://github.com/TheR1D/shell_gpt/assets/54123668/f4b3f5b3-fc43-44e9-b7be-8f4e267c2cb1)
is 0 requests it is too much ? I don't think  so

**Comment by israellevin** [comment]
I'm getting the same error - it has nothing to do with the actual limits. I have no problems using https://github.com/0xacx/chatGPT-shell-cli, for example.
