### ISSUE TITLE
HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/completions

### ISSUE THREAD

**Issue by designium** [TheR1D/shell_gpt#21]
After adding my API secret and making one request, I get this error message. I tried the following command:

    sgpt "nginx default config file location"

**Comment by TheR1D** [comment]
Usually it happens because of OpenAI API limitations. You can read more about request limits [here](https://platform.openai.com/docs/guides/rate-limits/overview)
You can track your usage in the [dashboard](https://platform.openai.com/account/usage)
Note that limitation applies on both [OpenAI's playground](https://platform.openai.com/playground) and this tools which is  using their API.

Duplicate https://github.com/TheR1D/shell_gpt/issues/13

**Comment by Bide-UK** [comment]
I can confirm that `429 - Rate limit reached` for requests is not always due to a local rate limit being hit as I opened my machine this morning, ran the command and got the status code immediately. I would also hazard a guess that this is still an issue predominantly on openAI's side due to traffic however.

**Comment by designium** [comment]
Thanks! I think it's the limit; I have to switch to paid API account. Thanks.

**Comment by TheR1D** [comment]
I'm reopening the issue to move it to the Open Issues section, so that others can see it before creating duplicate issues.

**Comment by kid-gorgeous** [comment]
Do you think changing the token request amount could help? I ran into the same problem. I reset my API key, and set my --maxtokens to 1024 just to be safe

**Comment by TheR1D** [comment]
You can try different model, for example `--model curie`
