### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by kid-gorgeous** [TheR1D/shell_gpt#25]
I cant install this with the current command provide.. It never asked for my API key. When I tried running 
`python3 sgpt.py get_api_key` and adding it manually, it never took in my key.

**Comment by TheR1D** [comment]
@DanielVolz Read more here https://github.com/TheR1D/shell_gpt/issues/21 about `429 Client Error` issue.

If you installed `sgpt using pip3 install shell-gpt --user` and it does not run when you call it with `sgpt` in your shell, this likely means that your pip folder is not included in your $PATH environment variable.

To investigate further, please provide the output of the following commands:
```
echo $PATH
pip3 show shell-gpt
```

**Comment by DanielVolz** [comment]
Wow, what a fast reply!

I'am on macos. I dit try the `pip3 install shell-gpt --user --upgrade` command and it didn't help.
Here are the outputs:
pip3 show shell-gpt:

Name: shell-gpt
Version: 0.4.1
Summary: CLI App allows to query OpenAI GPT-3 models using API.
Home-page: https://github.com/ther1d/shell_gpt
Author: Farkhod Sadykov
Author-email: farkhod@sadykov.dev
License:
Location: /Users/danielvolz/Library/Python/3.11/lib/python/site-packages
Requires: requests, rich, typer
Required-by:

echo $PATH:
/usr/local/lib/python3.11/site-packages:/usr/local/opt/openjdk/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components


And yes, i'm also getting a "response = <Response [429]>" so then it must be a temporary error due to high traffic.

**Comment by TheR1D** [comment]
@DanielVolz 
Try to install it without specifying `--user` parameter:
```
pip3 install shell-gpt --upgrade
```

**Comment by DanielVolz** [comment]
I solved the issue with the executable by running `python3 -m site --user-base` and adding `bin` to the result string. 
Finally adding it to my PATH variable like: `export PATH="/Users/danielvolz/Library/Python/3.11/bin:$PATH"`.

**Comment by kid-gorgeous** [comment]
Hey guys, sorry I was online yesterday. With the extra help from @DanielVolz, and @TheR1D the problem resolved. It seems like it must of been an issue with the executable path. 

With the following command line arguments I was able fix the issues: 
`pip show shell-gpt`
from there I was able to copy the PATH address and add it to the result string with:
`export = "<PATH_TO_EXECUTABLE>/bin/:$PATH"

Still working on add the api key, but I will close the issues for right now. 

Thank you all!!

**Comment by TheR1D** [comment]
Great! Closing the issue as solved.

**Comment by Sam-Pryor** [comment]
@DanielVolz 's solution worked for me on Pop!_OS

1) get the path with 
`python3 -m site --user-base`
e.g.
`#/home/sam/.local`

2) add the path adding /bin:
`export PATH="/home/sam/.local/bin:$PATH"`

3) If that works, it will only work for the current shell session.
To make it load on every session you'll need to add the same export command into your ~/.bashrc file.
