### ISSUE TITLE
Execute not work

### ISSUE THREAD

**Issue by wybert** [TheR1D/shell_gpt#255]
see below, I am using Macbook M1, fish shell.
<img width="525" alt="image" src="https://github.com/TheR1D/shell_gpt/assets/5254627/f3483e68-3ec8-42a7-b2b9-13230efbf67c">

**Comment by mountaineerbr** [comment]
In this case, the programme may indeed `cd` into any directory and you would not see it with `pwd`, because `sgpt` is run in a _shell fork_ (subshell), thus even thou `cd` is executed, it does not change directory of the parent shell.

Maybe if you use the programme in multi-turn mode? So that all commands are run in the same shell level? Even then, I am not sure `sgpt` can run multiple-turn commands in the same subshell, anyways..

**Comment by wybert** [comment]
I see. thanks for explaining.
