### ISSUE TITLE
Render markdown output

### ISSUE THREAD

**Issue by volkov** [TheR1D/shell_gpt#333]
Currently output of command is not formated by default
![image](https://github.com/TheR1D/shell_gpt/assets/459989/c24e82f1-d096-4b90-87a7-5bbbd2a303a7)

It would be more readable if use something like `glow` formatting (although glow is written in go - so some alternative should be found)
![image](https://github.com/TheR1D/shell_gpt/assets/459989/241eca61-1635-4d0b-ab9d-980ae988c94b)

**Comment by TheR1D** [comment]
We can pipe output of `sgpt` to `glow` or any other markdown reader.
```shell
sgpt "how to zip all files in current folder" | glow
```

**Comment by volkov** [comment]
True, at least for latest glow versions (1.4.0 does not support stdin).

**Comment by David-Else** [comment]
How about https://github.com/swsnr/mdcat?

**Comment by jeanlucthumm** [comment]
https://rich.readthedocs.io/en/stable/markdown.html

^ python lib for markdown rendering with code syntax highlighting

**Comment by jeanlucthumm** [comment]
The line that prints messages seems to be this one:

https://github.com/TheR1D/shell_gpt/blob/1c585664889e2cfb19ca1e13f0e8d621463ddef3/sgpt/handlers/handler.py#L34

Gonna try to change it to the Rich markdown handler and see what happens

**Comment by jeanlucthumm** [comment]
To deal with the streaming, one option is to detect beginning of special blocks, like a code block, and then automatically append a closing statement until we get the actual one from the llm. We'd have to identify all such blocks.

Another consideration is how slow the markdown render is. It has to fully complete for every word streamed in which is multiple times per second.

**Comment by jeanlucthumm** [comment]
I found the `DISABLE_STREAMING` option and at the very least, it's possible to output markdown if that's enabled:



https://github.com/TheR1D/shell_gpt/assets/4934853/d715bad9-01c6-4618-aa26-9607b76bafb7



Code: https://github.com/jeanlucthumm/shell_gpt/commit/eed0f7e813ab61a3c653ef2b03b34a4329ddd6ee

I'm not sure how I feel about the long waiting times though.

Other than that, I think you would need a full screen TUI to pull this off because you have to clear and repain the markdown file as words come in, but only from the current line down. The only thing I found was clearning the entire screen using `console.clear()`, and while that works, you lose all your history.

**Comment by gwpl** [comment]
sounds like invitaiton for `--glow` and `--no-glow` options! (and default in config file "DEFAULT_GLOW=true|false"

**Comment by thdonatello** [comment]
@diegodario88 did you fix it?

**Comment by diegodario88** [comment]
@thdonatello no, not yet.
