### ISSUE TITLE
⚠️ Please check our wiki page before creating new issue

### ISSUE THREAD

**Issue by TheR1D** [TheR1D/shell_gpt#37]
Please check our [wiki](https://github.com/TheR1D/shell_gpt/wiki) before creating new issue.

**Comment by DanielVolz** [comment]
I have a general question: Is this application intended to be used with a paid API key? 

Because I have a free OpenAI account without any credits on it and this application, whenever I tried to use it, throws a 429 error code.

I use another ChatGPT cli application (https://github.com/acheong08/ChatGPT/) with the option to login via username and password credentials and this application actually works most of the time.
