### ISSUE TITLE
I tested 'Simple query' noted on Markdown, but infinity code generated

### ISSUE THREAD

**Issue by mindgitrwx** [TheR1D/shell_gpt#40]
<img width="590" alt="screenshot 2023-02-25 at 1 50 12 PM" src="https://user-images.githubusercontent.com/37054916/221338952-35040dca-3bec-441e-b07b-ef8efecb7e73.png">

I just submitted `sgpt "mass of sun"`, but too much length of prompt has been generated.

**Comment by TheR1D** [comment]
This can happen because GPT-3 models work probabilistically, meaning that they're not always going to give you the same answer. Also, they're trained on a lot of data, so sometimes they might pick up on slightly different patterns or trends, which can affect the output they generate.

If you're looking for the most probable or accurate output, setting a lower temperature and a higher top_p value might be a good starting point. For example: `sgpt --temperature 0.4 "mass of sun"`
