### ISSUE TITLE
Integration tests refactoring

### ISSUE THREAD

**Issue by LeuschkeTressa** [TheR1D/shell_gpt#419]
I was considering contributing some refactoring of the integration tests; something like speeding them up (there's some low hanging fruit there), adding some structure, dropping the unittest imports in favour of pytest functionality and incorporating some other testing best practices. I also see a possibility of reducing the test code LOC (without testing less).

Would such a PR be welcome?

If so, any other guidelines/preferences around the tests that could be useful for me to know in advance?

@TheR1D

**Comment by TheR1D** [comment]
Would be great to refactor current tests, since they are not well written. LOC code optimisations are always welcome. There are few resources might be usefull:
* [Typer testing](https://typer.tiangolo.com/tutorial/testing/) 
* [OpenAI tests](https://github.com/openai/openai-python/blob/main/tests/test_client.py)

We also have a [unit test module](https://github.com/TheR1D/shell_gpt/blob/main/tests/test_unit.py) where we can add more  tests with mocked responses (as OpenAI tests).
