### ISSUE TITLE
Add option to turn off markdown formater

### ISSUE THREAD

**Issue by edshamis** [TheR1D/shell_gpt#438]
I need to pipe sgpt output, now the md formatter removes md symbols which I want to be preserved in the pipe

**Comment by jeanlucthumm** [comment]
https://github.com/TheR1D/shell_gpt/issues/423#issuecomment-1892219962

**Comment by TheR1D** [comment]
This feature was added in [1.3.0](https://github.com/TheR1D/shell_gpt/releases/tag/1.3.0).

> Markdown formatting now depends on the role description. For instance, if the role includes "APPLY MARKDOWN" in its description, the output for this role will be Markdown-formatted. This applies to both default and custom roles. If you would like to disable Markdown formatting, edit the default role description in ~/.config/shell_gpt/roles.

But it is probably a good idea to disable it based on `sys.stdout.isatty()` as @jeanlucthumm mentioned. But I'm not sure how exactly we should implement it, since we specifcally requiring Markdown in the role description.

**Comment by ryanfreckleton** [comment]
I was about to request this. Yes, the issue isn't markdown output, but the formatter, [Rich](https://rich.readthedocs.io/en/stable/introduction.html), I think?

Outputting Markdown format without going through Rich would enable me to use it a lot more easily as part of my flow.

**Comment by TheR1D** [comment]
Released in [1.4.0](https://github.com/TheR1D/shell_gpt/releases/tag/1.4.0).
