### ISSUE TITLE
Failed integration with ZSH

### ISSUE THREAD

**Issue by aramacs** [TheR1D/shell_gpt#582]
Hey I tried to find a solution but not worked out. I'm trying to configure it shell integration. 
![image](https://github.com/TheR1D/shell_gpt/assets/69637662/a37ffed0-07c3-4da0-98d2-c22507e974ed)

**Comment by schwab** [comment]
I get the same error in Ubuntu with ZSH.  Any ideas on this one?

**Comment by aramacs** [comment]
Not yet. Here I'm on arch.

**Comment by danjeltahko** [comment]
Can you have a look on what version you are using?

**Comment by aramacs** [comment]
Here I'm on it

![image](https://github.com/TheR1D/shell_gpt/assets/69637662/d9631009-22fe-4e79-8e77-de966dbd9f7d)

**Comment by danjeltahko** [comment]
Alright you have the latest version so i did some investigation, to cross check if the issue is because of the latest fix not being included you could run:
`sed -n 67,87p /usr/local/lib/python3.10/dist-packages/sgpt/utils.py`

or if you have installed it without sudo (at least for me):
`sed -n 67,87p ~/.local/lib/python3.10/site-packages/sgpt/utils.py`

if the printed code snippet shows "if shell == "/bin/zsh" instead of "if "zsh" in shell" you will need to uninstall sgpt with either
`pip3 uninstall shell_gpt`
or
`sudo pip3 unisntall shell_gpt`
depending on how you installed it.

I'm using pop_os without really any configuration so only sudo will have it on PATH. After that reinstall sgpt with:
`sudo pip3 install git+https://github.com/TheR1D/shell_gpt@main`
or without sudo if you have your home local in path.

If this doesn't solve the problem, then i actually don't know what the issue is.. Hope it works :)

**Comment by aramacs** [comment]
![image](https://github.com/TheR1D/shell_gpt/assets/69637662/7b7ba95e-8dc9-40b7-9aa6-d31d9417546e)
I don't get that return in either of them. I installed using pipx perhaps I should do something different?

**Comment by danjeltahko** [comment]
To see which directory you actually have your sgpt in, you could run :
```
> python3 -m pip show shell_gpt

Name: shell_gpt
Version: 1.4.3
Summary: A command-line productivity tool powered by large language models, will help you accomplish your tasks faster and more efficiently.
Home-page: https://github.com/ther1d/shell_gpt
Author:
Author-email: Farkhod Sadykov <farkhod@sadykov.dev>
License:
Location: /opt/homebrew/lib/python3.11/site-packages
Requires: click, distro, instructor, openai, rich, typer
Required-by:
```
and in my case i have it in brew, so for me, as you can see above, i would print out the code with:
`sed -n 67,87p /opt/homebrew/lib/python3.11/site-packages/sgpt/utils.py`

But please try to unisntall and reinstall from github link pointing to latest commit on main branch. I think that will solve the problem.

**Comment by aramacs** [comment]
I get that: 

![image](https://github.com/TheR1D/shell_gpt/assets/69637662/8a2ba360-cd54-4a4f-9d1b-5e5fd668ea35)

**Comment by danjeltahko** [comment]
Arch.. Well you can either create an environemnt and always have that activated, wait for the next release tag, or add a flag to you pip installation.

### install the package for your user only, bypassing the system-wide restrictions.
`sudo pip3 install --user git+https://github.com/TheR1D/shell_gpt@main`

### override the system package management and install the package directly
`sudo pip3 install git+https://github.com/TheR1D/shell_gpt@main --break-system-packages`

**Comment by aramacs** [comment]
The installation work out. But when I refresh my terminal I get that error

**Comment by danjeltahko** [comment]
Try changing the line to:
`bindkey '^l' _sgpt_zsh`
If that doesn't work, please ask sgpt how to solve it..

**Comment by aramacs** [comment]
Thanks for your help.
